info:
  description: Training configuration repo

---
spring:
  profiles: cloud
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:ifoundit@eureka-config-server-unpermeable-tetrahedrite.cfapps.io/eureka
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  
feign:
  hystrix:
    enabled: true

