info:
  description: Training configuration repo

---
spring:
  profiles: cloud
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:ifoundit@eureka-config-server-commeasurable-sufficiency.cfapps.io/eureka
