# Hibernate ddl auto (create, create-drop, update)
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: NON_NULL

endpoints:
  sensitive: false

server:
  port: 8100
