spring:
  cloud:
    config:
      server:
        git:
          uri: ${vap.services.config-repo-git.credentials.uri}

security:
  user:
    name: ${vap.services.config-basic-auth.credentials.username}
    password: ${vap.services.config-basic-auth.credentials.password}
